// <auto-generated />
namespace HRS.Web.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class mig11292017 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(mig11292017));
        
        string IMigrationMetadata.Id
        {
            get { return "201711291345468_mig11292017"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
