// <auto-generated />
namespace HRS.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class mig001raaz : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(mig001raaz));
        
        string IMigrationMetadata.Id
        {
            get { return "201701111406510_mig001-raaz"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
